# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='secret_key',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
