# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20170102_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
