# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='admin-base-base-time-model-created')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='admin-base-base-time-model-changed')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('datetime', models.DateTimeField(verbose_name='Datum a čas')),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField()),
                ('is_published', models.DateTimeField(auto_now_add=True)),
                ('is_promoted', models.IntegerField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
