# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
