# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 09:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161015_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='perex',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
