# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 09:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_perex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(default='', verbose_name='admin-events-description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='perex',
            field=tinymce.models.HTMLField(default='', verbose_name='admin-events-perex'),
        ),
    ]
