# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import project.events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, storage=project.events.models.ImageStorage(base_url='/media/image', location='/home/dorian/Work/wp/Meteleska/python-meteleska/project/media/image'), upload_to=project.events.models.Event.upload_to, verbose_name='admin-events-image'),
        ),
    ]
