# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concerts/', verbose_name='admin-events-image'),
        ),
    ]
