# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/concerts/', verbose_name='admin-events-image'),
        ),
    ]
