# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='admin-base-base-time-model-created')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='admin-base-base-time-model-changed')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('content', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
