# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'True or False')], default=0),
        ),
    ]
