# Generated by Django 3.0.2 on 2020-01-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20200105_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='project_name',
            new_name='site_name',
        ),
    ]
