# Generated by Django 3.0.2 on 2020-01-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='content',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='type',
        ),
    ]
