# Generated by Django 2.2.10 on 2020-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20200105_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='preference',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='preference',
            name='slogan',
            field=models.CharField(default='', help_text='Optional.', max_length=255),
        ),
    ]
