# Generated by Django 2.2.13 on 2020-07-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20200702_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo/', verbose_name='admin-events-logo'),
        ),
    ]
