# Generated by Django 2.2.13 on 2020-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_preference_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='description',
            field=models.CharField(default='', help_text='Optional.', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo/', verbose_name='admin-logo'),
        ),
    ]
