# Generated by Django 3.0.8 on 2020-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_auto_20200721_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='footer_slogan',
            field=models.CharField(default='', help_text='Optional.', max_length=255),
        ),
    ]
