# Generated by Django 3.0.8 on 2020-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_preference_footer_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional.', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='footer_slogan',
            field=models.CharField(blank=True, default='', help_text='Optional.', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='slogan',
            field=models.CharField(blank=True, default='', help_text='Optional.', max_length=255),
        ),
    ]
