# Generated by Django 3.0.8 on 2020-08-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0011_preference_footer_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='press_zip_file',
            field=models.FileField(blank=True, help_text='ZIP file with high quality photos & logos', null=True, upload_to='files/', verbose_name='Press Photos'),
        ),
        migrations.AddField(
            model_name='preference',
            name='rider_file',
            field=models.FileField(blank=True, help_text='Rider - technical and other demands for promoters.', null=True, upload_to='files/', verbose_name='Rider'),
        ),
    ]
