# Generated by Django 3.0.8 on 2020-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0012_auto_20200806_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='logo_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Logo for download.'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='press_zip_file',
            field=models.FileField(blank=True, help_text='ZIP file with high quality photos.', null=True, upload_to='files/', verbose_name='Press Photos'),
        ),
    ]
