# Generated by Django 3.0.8 on 2020-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0013_auto_20200806_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='title_slogan',
            field=models.CharField(blank=True, default='', help_text="Visible on homepage in browser's title or favourites.", max_length=100),
        ),
        migrations.AlterField(
            model_name='preference',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Visible in Google on basic search.', max_length=255),
        ),
    ]
