# Generated by Django 3.1.1 on 2020-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0015_preference_show_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=16),
        ),
        migrations.AddField(
            model_name='preference',
            name='secondary_color',
            field=models.CharField(default='#c0c0c0', max_length=16),
        ),
    ]
