# Generated by Django 3.1.1 on 2020-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0016_auto_20200916_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
    ]
