# Generated by Django 2.2.13 on 2020-07-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20200209_1301'),
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PykapelaGallery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('photologue.gallery',),
        ),
    ]
