# Generated by Django 3.0.8 on 2020-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Modules available: homepage, events, music, news, gallery, bio, contact, Add these pages with equivalent position to match background images.', null=True),
        ),
    ]
