# Generated by Django 3.1.1 on 2020-09-12 08:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200911_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_cs',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_cs',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='portrait_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pages/', verbose_name='Portrait Image (optional)'),
        ),
    ]
