# Generated by Django 3.1.1 on 2020-09-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200916_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
