# Generated by Django 3.0.2 on 2020-01-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='admin-base-base-time-model-created')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='admin-base-base-time-model-changed')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=56, verbose_name='System name, "facebook" for example')),
                ('url', models.CharField(max_length=256)),
                ('secret_key', models.CharField(blank=True, default='', max_length=256)),
                ('is_promoted', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('widget_code', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
