# Generated by Django 3.0.2 on 2020-01-05 20:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='admin-base-base-time-model-created')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='admin-base-base-time-model-changed')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('datetime', models.DateTimeField(verbose_name='Starts at')),
                ('location', models.CharField(default='', max_length=256, verbose_name='Name of a club or festival')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('description', tinymce.models.HTMLField(blank=True, default='', verbose_name='Event description (optional)')),
                ('slug', models.SlugField(verbose_name='URL slug')),
                ('is_published', models.BooleanField(default=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/concerts/', verbose_name='admin-events-image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
