# Generated by Django 3.1.1 on 2020-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200911_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Link to Facebook Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Promoted events will be first and first is bigger with picture. Otherwise sorted by datetime'),
        ),
    ]
